version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
      nodejs: 16
    commands:
      - npm install
      - composer install
  build:
    commands:
      - zip -r my-app.zip src/* vendor/* index.php
artifacts:
  files:
    - my-app.zip