version: 0.2

phases:
  install:
    commands:
  build:
    commands:
      - zip -r app.zip ./*
      - curl -sS https://getcomposer.org/installer -o composer-setup.php
      - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - curl -sL https://rpm.nodesource.com/setup_16.x | -E bash -
      - cd /var/www/html
      - unzip app.zip src/*
      - npm install
      - composer install --prefer-dist --no-interaction
artifacts:
  files:
    - app.zip