version: 0.2

phases:
  pre_build:
    commands:
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - composer --version
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - composer install --no-scripts
      - zip -r my-app.zip .
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - my-app.zip