version: 0.2

phases:
  pre_build:
    commands:
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar self-update
      - php composer.phar check-platform-reqs
      - php composer.phar install --ignore-platform-reqs
  build:
    commands:
      - zip -r my-app.zip .
artifacts:
  files:
    - my-app.zip