version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
      nodejs: 12
    commands:
      - npm install
      - php composer-setup.php --version=<version>
      - php -r "unlink('composer-setup.php');"
      - php composer.phar --version
      - composer install --ignore-platform-reqs --verbose
  build:
    commands:
      - zip -r my-app.zip src/* vendor/* index.php
artifacts:
  files:
    - my-app.zip