version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install
  build:
    commands:
      - zip -r my-app.zip .
      - sudo rm -rf /var/www/html/*
      - sudo unzip -o my-app.zip -d /var/www/html/
      - sudo chown -R www-data:www-data /var/www/html
      - sudo chmod -R 755 /var/www/html

artifacts:
  files:
    - my-app.zip