version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
      nodejs: 12
    commands:
      - npm install
      - composer install --ignore-platform-reqs
  build:
    commands:
      - zip -r my-app.zip src/* vendor/* index.php
artifacts:
  files:
    - my-app.zip