version: 0.2

phases:
  install:
    commands:
  build:
    commands:
      - zip -r app.zip ./*
      - cd /var/www/html
      - unzip app.zip src/*
      - npm install
      - composer install --prefer-dist --no-interaction
artifacts:
  files:
    - app.zip