on: push
name: CI
defaults:
  run:
    working-directory: ./old_src

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install Dependencies
      run: composer install --no-scripts

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        APP_KEY: base64:ZFVuxXwbURJDO7dSN/LIGfvK+8cA7fdXDQtWTF3sOaY=
      run: |
        php artisan migrate --seed --force
        php artisan passport:install
        vendor/bin/phpunit tests/
